### ISSUE TITLE
project/binary name collides with an established project/binary

### ISSUE THREAD

**Issue by vbatts** [cyphar/orca-build#1]
https://wiki.gnome.org/Projects/Orca
it's a screen reader for accessibility. 

While testing orca.py, in error was calling the screen reader, and had an existential moment of trying to figure out how the Dockerfile build was corresponding to my behavior on the desktop. :rofl:

**Comment by cyphar** [comment]
As with all good projects, one of the first issues is that the name sucks (opencontainers/runc#24).

Would `orca-build` be better? I kinda like the fact that `docker build` -> `orca` for obvious reasons. ;)

**Comment by vbatts** [comment]
perhaps that would be fine

**Comment by cyphar** [comment]
Fixed in 1afe3b9bbb16d6e346e084132b6f7ae5a3566bcf. Thanks @vbatts.
