### ISSUE TITLE
broken link in doc

### ISSUE THREAD

**Issue by MalloZup** [cyphar/orca-build#12]
here:
https://hackweek.suse.com/15/projects/orca-build-oci-images-from-dockerfiles

**Comment by cyphar** [comment]
Hmmm, it looks like https://hackweek.suse.com/ is down. I'll ping the appropriate people.

**Comment by MalloZup** [comment]
@cyphar sure, ok then feel free to close the issue, and open in proper place.i didn't ping the  whole server
🐼
